version: '3'

services:
  naming-server:
    build: ./docker/ns
    restart: always
    container_name: ns
    image: themavl/dfs-ns
    command: python -u dfs_ns.py

    environment:
      HOSTING: aws-many
      PRIVATE_PORT: 33333
      PUBLIC_PORT: 23333

    ports:
      - 23333:23333
      - 33333:33333

    volumes:
      - ./docker/ns:/src

  storage-server:
    build: ./docker/ss
    # restart: always
    container_name: ss1
    image: themavl/dfs-ss
    
    command: python -u dfs_ss.py

    environment:
      HOSTING: aws-many
      PUBLIC_PORT: 23334
      PRIVATE_PORT: 33334
      NS_PRIVATE_ADDRESS: 172.31.24.157:33333

    ports:
      - 23334:23334
      - 33334:33334

    volumes:
      - ./docker/ss:/src