# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import dfs_pb2 as dfs__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class DFS_NamingServerStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.init = channel.unary_unary(
        '/DFS_NamingServer/init',
        request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        response_deserializer=dfs__pb2.GenericResponse.FromString,
        )
    self.ls = channel.unary_unary(
        '/DFS_NamingServer/ls',
        request_serializer=dfs__pb2.Path.SerializeToString,
        response_deserializer=dfs__pb2.GenericResponse.FromString,
        )
    self.sl = channel.unary_stream(
        '/DFS_NamingServer/sl',
        request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        response_deserializer=dfs__pb2.SSSummary.FromString,
        )
    self.cd = channel.unary_unary(
        '/DFS_NamingServer/cd',
        request_serializer=dfs__pb2.Path.SerializeToString,
        response_deserializer=dfs__pb2.GenericResponse.FromString,
        )
    self.rm = channel.unary_unary(
        '/DFS_NamingServer/rm',
        request_serializer=dfs__pb2.Path.SerializeToString,
        response_deserializer=dfs__pb2.GenericResponse.FromString,
        )
    self.cp = channel.unary_unary(
        '/DFS_NamingServer/cp',
        request_serializer=dfs__pb2.Path2.SerializeToString,
        response_deserializer=dfs__pb2.GenericResponse.FromString,
        )
    self.mv = channel.unary_unary(
        '/DFS_NamingServer/mv',
        request_serializer=dfs__pb2.Path2.SerializeToString,
        response_deserializer=dfs__pb2.GenericResponse.FromString,
        )
    self.which = channel.unary_unary(
        '/DFS_NamingServer/which',
        request_serializer=dfs__pb2.Path.SerializeToString,
        response_deserializer=dfs__pb2.GenericResponse.FromString,
        )
    self.which_chunk = channel.unary_stream(
        '/DFS_NamingServer/which_chunk',
        request_serializer=dfs__pb2.ChunkUUID.SerializeToString,
        response_deserializer=dfs__pb2.SSSummary.FromString,
        )
    self.info = channel.unary_unary(
        '/DFS_NamingServer/info',
        request_serializer=dfs__pb2.Path.SerializeToString,
        response_deserializer=dfs__pb2.GenericResponse.FromString,
        )
    self.mkdir = channel.unary_unary(
        '/DFS_NamingServer/mkdir',
        request_serializer=dfs__pb2.Path.SerializeToString,
        response_deserializer=dfs__pb2.GenericResponse.FromString,
        )
    self.touch = channel.unary_unary(
        '/DFS_NamingServer/touch',
        request_serializer=dfs__pb2.Path.SerializeToString,
        response_deserializer=dfs__pb2.TouchResult.FromString,
        )
    self.rename = channel.unary_unary(
        '/DFS_NamingServer/rename',
        request_serializer=dfs__pb2.Path2.SerializeToString,
        response_deserializer=dfs__pb2.GenericResponse.FromString,
        )


class DFS_NamingServerServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def init(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ls(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def sl(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def cd(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def rm(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def cp(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def mv(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def which(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def which_chunk(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def info(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def mkdir(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def touch(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def rename(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_DFS_NamingServerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'init': grpc.unary_unary_rpc_method_handler(
          servicer.init,
          request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
          response_serializer=dfs__pb2.GenericResponse.SerializeToString,
      ),
      'ls': grpc.unary_unary_rpc_method_handler(
          servicer.ls,
          request_deserializer=dfs__pb2.Path.FromString,
          response_serializer=dfs__pb2.GenericResponse.SerializeToString,
      ),
      'sl': grpc.unary_stream_rpc_method_handler(
          servicer.sl,
          request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
          response_serializer=dfs__pb2.SSSummary.SerializeToString,
      ),
      'cd': grpc.unary_unary_rpc_method_handler(
          servicer.cd,
          request_deserializer=dfs__pb2.Path.FromString,
          response_serializer=dfs__pb2.GenericResponse.SerializeToString,
      ),
      'rm': grpc.unary_unary_rpc_method_handler(
          servicer.rm,
          request_deserializer=dfs__pb2.Path.FromString,
          response_serializer=dfs__pb2.GenericResponse.SerializeToString,
      ),
      'cp': grpc.unary_unary_rpc_method_handler(
          servicer.cp,
          request_deserializer=dfs__pb2.Path2.FromString,
          response_serializer=dfs__pb2.GenericResponse.SerializeToString,
      ),
      'mv': grpc.unary_unary_rpc_method_handler(
          servicer.mv,
          request_deserializer=dfs__pb2.Path2.FromString,
          response_serializer=dfs__pb2.GenericResponse.SerializeToString,
      ),
      'which': grpc.unary_unary_rpc_method_handler(
          servicer.which,
          request_deserializer=dfs__pb2.Path.FromString,
          response_serializer=dfs__pb2.GenericResponse.SerializeToString,
      ),
      'which_chunk': grpc.unary_stream_rpc_method_handler(
          servicer.which_chunk,
          request_deserializer=dfs__pb2.ChunkUUID.FromString,
          response_serializer=dfs__pb2.SSSummary.SerializeToString,
      ),
      'info': grpc.unary_unary_rpc_method_handler(
          servicer.info,
          request_deserializer=dfs__pb2.Path.FromString,
          response_serializer=dfs__pb2.GenericResponse.SerializeToString,
      ),
      'mkdir': grpc.unary_unary_rpc_method_handler(
          servicer.mkdir,
          request_deserializer=dfs__pb2.Path.FromString,
          response_serializer=dfs__pb2.GenericResponse.SerializeToString,
      ),
      'touch': grpc.unary_unary_rpc_method_handler(
          servicer.touch,
          request_deserializer=dfs__pb2.Path.FromString,
          response_serializer=dfs__pb2.TouchResult.SerializeToString,
      ),
      'rename': grpc.unary_unary_rpc_method_handler(
          servicer.rename,
          request_deserializer=dfs__pb2.Path2.FromString,
          response_serializer=dfs__pb2.GenericResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'DFS_NamingServer', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class DFS_NSPrivateStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.touch = channel.unary_unary(
        '/DFS_NSPrivate/touch',
        request_serializer=dfs__pb2.Path.SerializeToString,
        response_deserializer=dfs__pb2.TouchResult.FromString,
        )
    self.which_chunk = channel.unary_stream(
        '/DFS_NSPrivate/which_chunk',
        request_serializer=dfs__pb2.ChunkUUID.SerializeToString,
        response_deserializer=dfs__pb2.SSSummary.FromString,
        )
    self.SSLogin = channel.unary_unary(
        '/DFS_NSPrivate/SSLogin',
        request_serializer=dfs__pb2.SSLoginInfo.SerializeToString,
        response_deserializer=dfs__pb2.GenericResponse.FromString,
        )
    self.SSSync = channel.stream_stream(
        '/DFS_NSPrivate/SSSync',
        request_serializer=dfs__pb2.SyncChunkUUID.SerializeToString,
        response_deserializer=dfs__pb2.Update.FromString,
        )
    self.SSGotChunk = channel.unary_unary(
        '/DFS_NSPrivate/SSGotChunk',
        request_serializer=dfs__pb2.SyncChunkUUID.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.SSFileUpdate = channel.unary_unary(
        '/DFS_NSPrivate/SSFileUpdate',
        request_serializer=dfs__pb2.SSFileUpdateInfo.SerializeToString,
        response_deserializer=dfs__pb2.GenericResponse.FromString,
        )
    self.SSBeat = channel.unary_unary(
        '/DFS_NSPrivate/SSBeat',
        request_serializer=dfs__pb2.SSBeatInfo.SerializeToString,
        response_deserializer=dfs__pb2.GenericResponse.FromString,
        )
    self.SSGotWrite = channel.unary_unary(
        '/DFS_NSPrivate/SSGotWrite',
        request_serializer=dfs__pb2.SSGotWriteInfo.SerializeToString,
        response_deserializer=dfs__pb2.GenericResponse.FromString,
        )


class DFS_NSPrivateServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def touch(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def which_chunk(self, request, context):
    """Returns private address
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SSLogin(self, request, context):
    """SS -> NS
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SSSync(self, request_iterator, context):
    """SS -> NS
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SSGotChunk(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SSFileUpdate(self, request, context):
    """SS -> NS
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SSBeat(self, request, context):
    """SS -> NS
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SSGotWrite(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_DFS_NSPrivateServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'touch': grpc.unary_unary_rpc_method_handler(
          servicer.touch,
          request_deserializer=dfs__pb2.Path.FromString,
          response_serializer=dfs__pb2.TouchResult.SerializeToString,
      ),
      'which_chunk': grpc.unary_stream_rpc_method_handler(
          servicer.which_chunk,
          request_deserializer=dfs__pb2.ChunkUUID.FromString,
          response_serializer=dfs__pb2.SSSummary.SerializeToString,
      ),
      'SSLogin': grpc.unary_unary_rpc_method_handler(
          servicer.SSLogin,
          request_deserializer=dfs__pb2.SSLoginInfo.FromString,
          response_serializer=dfs__pb2.GenericResponse.SerializeToString,
      ),
      'SSSync': grpc.stream_stream_rpc_method_handler(
          servicer.SSSync,
          request_deserializer=dfs__pb2.SyncChunkUUID.FromString,
          response_serializer=dfs__pb2.Update.SerializeToString,
      ),
      'SSGotChunk': grpc.unary_unary_rpc_method_handler(
          servicer.SSGotChunk,
          request_deserializer=dfs__pb2.SyncChunkUUID.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'SSFileUpdate': grpc.unary_unary_rpc_method_handler(
          servicer.SSFileUpdate,
          request_deserializer=dfs__pb2.SSFileUpdateInfo.FromString,
          response_serializer=dfs__pb2.GenericResponse.SerializeToString,
      ),
      'SSBeat': grpc.unary_unary_rpc_method_handler(
          servicer.SSBeat,
          request_deserializer=dfs__pb2.SSBeatInfo.FromString,
          response_serializer=dfs__pb2.GenericResponse.SerializeToString,
      ),
      'SSGotWrite': grpc.unary_unary_rpc_method_handler(
          servicer.SSGotWrite,
          request_deserializer=dfs__pb2.SSGotWriteInfo.FromString,
          response_serializer=dfs__pb2.GenericResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'DFS_NSPrivate', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class DFS_StorageServerStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.has = channel.unary_unary(
        '/DFS_StorageServer/has',
        request_serializer=dfs__pb2.ChunkUUID.SerializeToString,
        response_deserializer=dfs__pb2.GenericResponse.FromString,
        )
    self.get = channel.unary_stream(
        '/DFS_StorageServer/get',
        request_serializer=dfs__pb2.ChunkUUID.SerializeToString,
        response_deserializer=dfs__pb2.Chunk.FromString,
        )
    self.write = channel.stream_unary(
        '/DFS_StorageServer/write',
        request_serializer=dfs__pb2.Chunk.SerializeToString,
        response_deserializer=dfs__pb2.GenericResponse.FromString,
        )


class DFS_StorageServerServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def has(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def get(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def write(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_DFS_StorageServerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'has': grpc.unary_unary_rpc_method_handler(
          servicer.has,
          request_deserializer=dfs__pb2.ChunkUUID.FromString,
          response_serializer=dfs__pb2.GenericResponse.SerializeToString,
      ),
      'get': grpc.unary_stream_rpc_method_handler(
          servicer.get,
          request_deserializer=dfs__pb2.ChunkUUID.FromString,
          response_serializer=dfs__pb2.Chunk.SerializeToString,
      ),
      'write': grpc.stream_unary_rpc_method_handler(
          servicer.write,
          request_deserializer=dfs__pb2.Chunk.FromString,
          response_serializer=dfs__pb2.GenericResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'DFS_StorageServer', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class DFS_SSPrivateStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Sync = channel.stream_unary(
        '/DFS_SSPrivate/Sync',
        request_serializer=dfs__pb2.Update.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
    self.get = channel.unary_stream(
        '/DFS_SSPrivate/get',
        request_serializer=dfs__pb2.ChunkUUID.SerializeToString,
        response_deserializer=dfs__pb2.Chunk.FromString,
        )
    self.has = channel.unary_unary(
        '/DFS_SSPrivate/has',
        request_serializer=dfs__pb2.ChunkUUID.SerializeToString,
        response_deserializer=dfs__pb2.GenericResponse.FromString,
        )
    self.Nuke = channel.unary_unary(
        '/DFS_SSPrivate/Nuke',
        request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )


class DFS_SSPrivateServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Sync(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def get(self, request, context):
    """For private address
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def has(self, request, context):
    """For private address
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Nuke(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_DFS_SSPrivateServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Sync': grpc.stream_unary_rpc_method_handler(
          servicer.Sync,
          request_deserializer=dfs__pb2.Update.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
      'get': grpc.unary_stream_rpc_method_handler(
          servicer.get,
          request_deserializer=dfs__pb2.ChunkUUID.FromString,
          response_serializer=dfs__pb2.Chunk.SerializeToString,
      ),
      'has': grpc.unary_unary_rpc_method_handler(
          servicer.has,
          request_deserializer=dfs__pb2.ChunkUUID.FromString,
          response_serializer=dfs__pb2.GenericResponse.SerializeToString,
      ),
      'Nuke': grpc.unary_unary_rpc_method_handler(
          servicer.Nuke,
          request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'DFS_SSPrivate', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
